let util = require('./index.js')
console.log(util.dashToCamelCase("my-first-name"))
console.log(util.camelCaseToDash("myFirstName"))
console.log(util.underscoreToCamelCase("my_first_name"))
console.log(util.camelCaseToUnderscore("myFirstName"))
